In [8]:
import pandas as pd

pd.set_option("display.min_rows", 30) #设置显示的最小行数(默认为10行)

# 1.读取数据
df = pd.read_csv('data/sales_data.csv')

# 2.数据清洗
# 2.1 缺失值处理
df.isnull()#检查是否有缺失值

# 2.1.1 删除缺失值
df.dropna()# 删除有缺失值的行
df1 = df.dropna(axis=1)# 删除有缺失值的列

# 2.1.2 填充缺失值
df.fillna("--")# 填充缺失值
df.ffill() # 运用前一个值进行填充
df.bfill() # 运用后一个值进行填充

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6039081663  家居用品    抱枕     8   62     合肥   支付宝  2025-06-19
1    6706070220  家居用品    枕头     3  268     昆明   支付宝  2025-06-01
2    6227000596    服装    围巾     8  162     北京  微信支付  2025-06-08
3    6707557512  电子产品    U盘     5  831     天津   支付宝  2025-06-07
4    5999170184    图书    字典    12  164     南京   支付宝  2025-06-22
5    6786607411    服装    T恤    13  170     武汉   银行卡  2025-06-20
6    6212936598  家居用品    枕头     8   50     武汉   支付宝  2025-06-26
7    6616314859  电子产品    耳机    12  413     重庆   银行卡  2025/06/03
8    5953335723    服装   牛仔裤    18  103     青岛    现金  2025-06-13
9    6379708537    服装    外套    11  417     上海  微信支付  2025-06-01
10   5868934737  电子产品    键盘     9 -985     福州   银行卡  2025-06-07
11   6616314859    图书    杂志    15   45     武汉   银行卡  2025-06-15
12   6720054627    服装    围巾    12   90     厦门    现金  2025-06-01
13   5995226476  家居用品  餐具套装     5  226     昆明   支付宝  2025-06-06
14   6626281506    图书   工具书    15  151     北京   支付宝  2025-06-19
..          ...   ...   ...   ...  ...    ...   ...         ...
985  6731576084    服装    袜子     1   26     成都    现金  2025-06-22
986  6788192558    图书   工具书    16  167     苏州    现金  2025-06-28
987  6449950228  家居用品    蜡烛     5   67     北京  微信支付  2025-06-13
988  5857585420    食品   巧克力     5   60     合肥  微信支付  2025-06-22
989  5984884489  电子产品    耳机     5   72     深圳  微信支付  2025-06-05
990  6127324261    图书    漫画    16  125     福州  微信支付  2025-06-13
991  6232370966  电子产品    手环    13   58     深圳    现金  2025-06-03
992  6692678677    图书   工具书    20   84     上海    现金  2025-06-15
993  6658307069    图书    传记    19  183     大连  微信支付  2025-06-12
994  5930362318    服装    袜子    14  303     广州   银行卡  2025-06-28
995  6695795860    图书    字典    16  175     苏州    现金  2025-06-01
996  6736796806  家居用品    蜡烛    10  250     苏州    现金  2025-06-11
997  6298437638    服装    外套    19  193     昆明    现金  2025-06-13
998  6081660873  电子产品    键盘    14  739     苏州    现金  2025-06-28
999  6147947649    服装    外套    10   64     大连  微信支付  2025-06-25

[1000 rows x 8 columns]

In [12]:
# 2.2 重复值处理
# 2.2.1 查看重复值
df.duplicated() # 检查是否有重复值(默认检查所有列)
df.duplicated(subset=["订单号"]) # 检查指定列是否有重复值


# 2.2.2 删除重复值
df.drop_duplicates(subset=["订单号"],keep="first") # keep='last' 保留最后出现的重复值; keep=False 删除所有重复值 ; keep='first' 保留第一个

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6039081663  家居用品    抱枕     8   62     合肥   支付宝  2025-06-19
1    6706070220  家居用品    枕头     3  268     昆明   支付宝  2025-06-01
2    6227000596    服装    围巾     8  162     北京  微信支付  2025-06-08
3    6707557512  电子产品    U盘     5  831     天津   支付宝  2025-06-07
4    5999170184    图书    字典    12  164     南京   支付宝  2025-06-22
5    6786607411    服装    T恤    13  170    NaN   银行卡  2025-06-20
6    6212936598  家居用品    枕头     8   50     武汉   支付宝  2025-06-26
7    6616314859  电子产品    耳机    12  413     重庆   银行卡  2025/06/03
8    5953335723    服装   牛仔裤    18  103     青岛    现金  2025-06-13
9    6379708537    服装    外套    11  417     上海  微信支付  2025-06-01
10   5868934737  电子产品    键盘     9 -985     福州   银行卡  2025-06-07
12   6720054627    服装    围巾    12   90     厦门    现金  2025-06-01
13   5995226476  家居用品  餐具套装     5  226     昆明   支付宝  2025-06-06
14   6626281506    图书   工具书    15  151     北京   支付宝  2025-06-19
15   6373002724  电子产品   路由器    10  514     北京   银行卡  2025-06-16
..          ...   ...   ...   ...  ...    ...   ...         ...
985  6731576084    服装    袜子     1   26     成都    现金  2025-06-22
986  6788192558    图书   工具书    16  167     苏州    现金  2025-06-28
987  6449950228  家居用品    蜡烛     5   67     北京  微信支付  2025-06-13
988  5857585420    食品   巧克力     5   60     合肥  微信支付  2025-06-22
989  5984884489  电子产品    耳机     5   72     深圳  微信支付  2025-06-05
990  6127324261    图书    漫画    16  125     福州  微信支付  2025-06-13
991  6232370966  电子产品    手环    13   58     深圳    现金  2025-06-03
992  6692678677    图书   工具书    20   84     上海    现金  2025-06-15
993  6658307069    图书    传记    19  183     大连  微信支付  2025-06-12
994  5930362318    服装    袜子    14  303     广州   银行卡  2025-06-28
995  6695795860    图书    字典    16  175     苏州    现金  2025-06-01
996  6736796806  家居用品    蜡烛    10  250     苏州    现金  2025-06-11
997  6298437638    服装    外套    19  193     昆明    现金  2025-06-13
998  6081660873  电子产品    键盘    14  739     苏州    现金  2025-06-28
999  6147947649    服装    外套    10   64     大连  微信支付  2025-06-25

[999 rows x 8 columns]

In [18]:
# 2.3 异常值处理
# 2.3.1 查看异常值
df.loc[df["单价"] < 0]


# 2.3.2 删除异常值
df.drop(df[df["单价"] < 0].index)

# 2.3.3 填充异常值
df["单价"] = df["单价"].abs()# 绝对值

In [20]:
# 2.4数据格式处理
# df['订单日期'] = df['订单日期'].replace('2023-01-01', '2023-01-01 00:00:00') # 替换,但不推荐
df['订单日期'] = df['订单日期'].str.replace('/','-')
df

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    6039081663  家居用品    抱枕     8   62     合肥   支付宝  2025-06-19
1    6706070220  家居用品    枕头     3  268     昆明   支付宝  2025-06-01
2    6227000596    服装    围巾     8  162     北京  微信支付  2025-06-08
3    6707557512  电子产品    U盘     5  831     天津   支付宝  2025-06-07
4    5999170184    图书    字典    12  164     南京   支付宝  2025-06-22
5    6786607411    服装    T恤    13  170    NaN   银行卡  2025-06-20
6    6212936598  家居用品    枕头     8   50     武汉   支付宝  2025-06-26
7    6616314859  电子产品    耳机    12  413     重庆   银行卡  2025-06-03
8    5953335723    服装   牛仔裤    18  103     青岛    现金  2025-06-13
9    6379708537    服装    外套    11  417     上海  微信支付  2025-06-01
10   5868934737  电子产品    键盘     9  985     福州   银行卡  2025-06-07
11   6616314859    图书    杂志    15   45     武汉   银行卡  2025-06-15
12   6720054627    服装    围巾    12   90     厦门    现金  2025-06-01
13   5995226476  家居用品  餐具套装     5  226     昆明   支付宝  2025-06-06
14   6626281506    图书   工具书    15  151     北京   支付宝  2025-06-19
..          ...   ...   ...   ...  ...    ...   ...         ...
985  6731576084    服装    袜子     1   26     成都    现金  2025-06-22
986  6788192558    图书   工具书    16  167     苏州    现金  2025-06-28
987  6449950228  家居用品    蜡烛     5   67     北京  微信支付  2025-06-13
988  5857585420    食品   巧克力     5   60     合肥  微信支付  2025-06-22
989  5984884489  电子产品    耳机     5   72     深圳  微信支付  2025-06-05
990  6127324261    图书    漫画    16  125     福州  微信支付  2025-06-13
991  6232370966  电子产品    手环    13   58     深圳    现金  2025-06-03
992  6692678677    图书   工具书    20   84     上海    现金  2025-06-15
993  6658307069    图书    传记    19  183     大连  微信支付  2025-06-12
994  5930362318    服装    袜子    14  303     广州   银行卡  2025-06-28
995  6695795860    图书    字典    16  175     苏州    现金  2025-06-01
996  6736796806  家居用品    蜡烛    10  250     苏州    现金  2025-06-11
997  6298437638    服装    外套    19  193     昆明    现金  2025-06-13
998  6081660873  电子产品    键盘    14  739     苏州    现金  2025-06-28
999  6147947649    服装    外套    10   64     大连  微信支付  2025-06-25

[1000 rows x 8 columns]